# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Intro to PHS"
  url = "intro-to-phs"
  weight = 1
  identifier = "intro-to-phs-parent"
  
  [[main]]
    name = "Welcome Slides"
    url = "/welcome-slides/introduction.pdf"
    parent = "intro-to-phs-parent"
    weight = 1

  [[main]]
    name = "Launch Slides"
    url = "/welcome-slides/launch-slides.pdf"
    parent = "intro-to-phs-parent"
    weight = 2

  [[main]]
    name = "Values Survey"
    url = "https://harvard.az1.qualtrics.com/jfe/form/SV_1RkvbQZsbAA3n5I"
    parent = "intro-to-phs-parent"
    weight = 3

  [[main]]
    name = "Self-Care Activities"
    url = "https://docs.google.com/document/d/1Fk_87N8liJ0P_5nAgCDThV-FRRTPoLw01gu2AKEEHYI/edit?usp=sharing"
    parent = "intro-to-phs-parent"
    weight = 4

[[main]]
  name = "Notation"
  url = "notation"
  weight = 2
  identifier = "notation-parent"
  
  [[main]]
    name = "Notation Slides"
    url = "/notation-slides/bootcamp_mathematicalNotation.pdf"
    parent = "notation-parent"
    weight = 1
  
  [[main]]
    name = "R Sweave Guide"
    url = "/sweave-guide/guide.pdf"
    parent = "notation-parent"
    weight = 2

[[main]]
  name = "Math"
  url = "math-review"
  weight = 3
  identifier = "math-review-parent"
  
  [[main]]
    name = "Math Slides"
    url = "/math-review-slides/math_review_2022.pdf"
    parent = "math-review-parent"
    weight = 1

[[main]]
  name = "Probability"
  url = "prob-review"
  weight = 4
  identifier = "prob-review-parent"
  
  [[main]]
    name = "Probability Slides"
    url = "/prob-slides/probability_2022.pdf"
    parent = "prob-review-parent"
    weight = 1

[[main]]
  name = "Inference Lite"
  url = "regressionEx"
  weight = 5
  identifier = "regExParent"
  
  [[main]]
    name = "Slides (pdf)"
    url = "/inference-lite/Covariance_Correlation.pdf"
    parent = "regExParent"
    weight = 1
  
[[main]]
  name = "Intro to R"
  url = "intro-to-r"
  weight = 6
  identifier = "intro-to-r-parent"
  
  [[main]]
    name = "Intro to R Slides"
    url = "/intro-to-r/R-setup-slides/R-setup.pdf"
    parent = "intro-to-r-parent"
    weight = 1
  
[[main]]
  name = "Feedback!"
  url = "https://docs.google.com/forms/d/e/1FAIpQLSfJbx49XQ_aoW_9yWbjS-fPYVSoKMz4myiEQFxJcgMoGBgazQ/viewform"
  weight = 7
  identifier = "feedback"

  # [[main]]
  #   name = "Github Repo"
  #   url = "https://github.com/jrcordes/Intro_to_R_SummR_Camp_2020"
  #   parent = "intro-to-r-parent"
  #   weight = 2

